[[redirects]]
  from = "http://milfoski.com/*"
  to = "https://milfoski.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/blog/sei-mio/"
  to = "/blog/non-si-puo-dire/"
  status = 301
