[[redirects]]
  from = "http://milfoski.com/*"
  to = "https://milfoski.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/blog/sei-mio/"
  to = "/blog/non-si-puo-dire/"
  status = 301

[[redirects]]
  from = "/blog/lorem-4/"
  to = "/404/"
  status = 410

[[redirects]]
  from = "/blog/lorem-1/"
  to = "/404/"
  status = 410

[[redirects]]
  from = "/blog/lorem-2/"
  to = "/404/"
  status = 410

[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404

[[headers]]
for = "/.well-known/nostr.json"
[headers.values]
Access-Control-Allow-Origin = "*"
Content-Type = "application/json"
